### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by darwintree**
Csv-related code is moved into CsvPanel component and transaction history is now supported.
Precison-related bugs are fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)

### CODE REVIEW

**Review by wangdayong228 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[frontend/src/App.vue, line 72 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_UvVfD9ecvTgXzFjrA:-M_UvVfE5MuRP9z_puaY:b-5eltaj) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L72)):*
> ```Vue
> 
>               <el-row type="flex">
>                 <el-col :span="7">代币余额（e18）</el-col>
> ```

remove e18
___
*[frontend/src/App.vue, line 508 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_VCevX8OlRaHItyXD1:-M_VCevX8OlRaHItyXD2:ba2i2r8) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L508)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
>         if (this.DEBUG){
>           this.transactionList.push({
>             hash: this.txHash,
>             csv: this.csv,
>             confirmDate: Date.now(),
>             selectedToken: this.selectedToken,
>             tokenAddress: this.contract.address,
>           })
>         }
>         this.notifyTxState()
>         receipt = await pendingTx.confirmed()
>         if (!this.DEBUG){
>           this.transactionList.push({
>             hash: this.txHash,
>             csv: this.csv,
>             confirmDate: Date.now(),
>             selectedToken: this.selectedToken,
>             tokenAddress: this.contract.address,
>           })
>         }
> ```
</details>

Is it repeat?

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: all files reviewed, 2 unresolved discussions (waiting on @darwintree and @wangdayong228)

___
*[frontend/src/App.vue, line 72 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_UvVfD9ecvTgXzFjrA:-M_V_equ3sEjFFCTpSeU:b-a9q4c4) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L72)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

remove e18
</blockquote></details>

working
___
*[frontend/src/App.vue, line 508 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_VCevX8OlRaHItyXD1:-M_V_WSq3agaUdmRUlio:bshr636) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L508)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

> ```
>         if (this.DEBUG){
>           this.transactionList.push({
>             hash: this.txHash,
>             csv: this.csv,
>             confirmDate: Date.now(),
>             selectedToken: this.selectedToken,
>             tokenAddress: this.contract.address,
>           })
>         }
>         this.notifyTxState()
>         receipt = await pendingTx.confirmed()
>         if (!this.DEBUG){
>           this.transactionList.push({
>             hash: this.txHash,
>             csv: this.csv,
>             confirmDate: Date.now(),
>             selectedToken: this.selectedToken,
>             tokenAddress: this.contract.address,
>           })
>         }
> ```
Is it repeat?
</blockquote></details>

this.DEBUG is initiallized to true if process.env.NODE_ENV !== ''production".
- So in debug environment, the former block will take effect: a new transaction will be pushed into transactionList after transaction is **executed**. 
- And in production environment, which means running `npm run build` command to get dist file, the transaction will be added to transactionList after transaction is **confirmed**.

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[frontend/src/App.vue, line 72 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_UvVfD9ecvTgXzFjrA:-M__LXUk2fslqgynggY4:b32w0x) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L72)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

working
</blockquote></details>

OK

**Review by wangdayong228 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: all files reviewed, 3 unresolved discussions (waiting on @wangdayong228)

___
*[frontend/src/App.vue, line 72 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_UvVfD9ecvTgXzFjrA:-M_eLM8WA-OK6GN68-5j:b-hf2aaa) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L72)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

OK
</blockquote></details>

Just remove it, erc777 token with cfx unit will make confuse
___
*[frontend/src/components/CsvPanel.vue, line 44 at r2](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_ePTpe7asP6PwBswhc:-M_ePTpe7asP6PwBswhd:b-5eltgi) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/222fca7d588aad69ddbd3c924679c9a1169c5951/frontend/src/components/CsvPanel.vue#L44)):*
> ```Vue
>           fixed
>           prop="value"
>           label="转账代币数量（CFX）"
> ```

remove cfx
___
*[frontend/src/components/HistoryTransactionLine.vue, line 33 at r2](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_ePa1F13fKxQ26QHVW:-M_ePa1F13fKxQ26QHVX:b-5eltgi) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/222fca7d588aad69ddbd3c924679c9a1169c5951/frontend/src/components/HistoryTransactionLine.vue#L33)):*
> ```Vue
>           fixed
>           prop="value"
>           label="转账代币数量（CFX）"
> ```

remove cfx

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @wangdayong228)

___
*[frontend/src/App.vue, line 72 at r1](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_UvVfD9ecvTgXzFjrA:-M_i67fGCldIFiYd-okX:b32wtd) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/71e7fb575bd539dbb1c3a06398d9c7f2eba7e360/frontend/src/App.vue#L72)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

Just remove it, erc777 token with cfx unit will make confuse
</blockquote></details>

ok
___
*[frontend/src/components/CsvPanel.vue, line 44 at r2](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_ePTpe7asP6PwBswhc:-M_i6BAw6lGU1RxGM1Dz:b32wtd) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/222fca7d588aad69ddbd3c924679c9a1169c5951/frontend/src/components/CsvPanel.vue#L44)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

remove cfx
</blockquote></details>

ok
___
*[frontend/src/components/HistoryTransactionLine.vue, line 33 at r2](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4#-M_ePa1F13fKxQ26QHVW:-M_i6BtH57z7GTxhU9B6:b32wtd) ([raw file](https://github.com/conflux-fans/tokenbatchsender/blob/222fca7d588aad69ddbd3c924679c9a1169c5951/frontend/src/components/HistoryTransactionLine.vue#L33)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

remove cfx
</blockquote></details>

ok

**Review by wangdayong228 — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/tokenbatchsender/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
